In [ ]:
import numpy as np
import pandas as pd

In [ ]:
x=np.array([[1],
            [2],
            [3]])
print(x)
x.shape


[[1]
 [2]
 [3]]


(3, 1)

Vertor-vector addition

In [ ]:
y=np.array([[4],[5],[6]])
z=x+y
#or 
q=np.add(x,y)
q



array([[5],
       [7],
       [9]])

Vector-scaler multiplication

In [ ]:
alpha=2
r=alpha*x
r

array([[2],
       [4],
       [6]])

Linear combination

In [ ]:
a, b=2,3
x, y=np.array([[1],[2]]), np.array([[3],[4]])
r=a*x+b*y
r

array([[11],
       [16]])

Vector-vector multiplication

In [ ]:
x.T@y
#or
np.dot(x.T, y)


array([[11]])

Vector space: \
a vector space is the set of proper vectors and all possible linear combinatios of the vector set. In addition, vector addition and multiplication must follow these eight rules:

commutativity: x + y = y + x\
associativity: x + (y + x) = (y + x) + z\
unique zero vector such that: $x + 0 = x$ $\forall$ $x$\
$\forall$ $x$ there is a unique vector $x$ such that $x + -x = 0$\
identity element of scalar multiplication: $1x = x$\
distributivity of scalar multiplication w.r.t vector addition: $x(y + z) = xz + zy$\
$x(yz) = (xy)z$\
$(y + z)x = yx + zx$



Vector norms:\
Measuring vectors is another important operation in machine learning applications. Intuitively, we can think about the norm or the length of a vector as the distance between its “origin” and its “end”.

Norms “map” vectors to non-negative values. In this sense are functions that assign length $\lVert \bf{x} \rVert \in \mathbb{R^n}$ to a vector $\bf{x}$. To be valid, a norm has to satisfy these properties (keep in mind these properties are a bit abstruse to understand):

Absolutely homogeneous: $\forall \alpha \in \mathbb{R}, \lVert \alpha \bf{x} \rVert = \vert \alpha \Vert \lVert \bf{x} \rVert$. In words: for all real-valued scalars, the norm scales proportionally with the value of the scalar.\
Triangle inequality: $\lVert \bf{x} + \bf{y} \rVert \le \lVert \bf{x} \rVert + \lVert \bf{y} \rVert $. In words: in geometric terms, for any triangle the sum of any two sides must be greater or equal to the lenght of the third side. This is easy to see experimentally: grab a piece of rope, form triangles of different sizes, measure all the sides, and test this property.\
Positive definite: $\lVert \bf{x} \rVert \ge 0$ and $ \lVert \bf{x} \rVert = 0 \Longleftrightarrow \bf{x}= 0$. In words: the length of any $\bf{x}$ has to be a positive value (i.e., a vector can’t have negative length), and a length of $0$ occurs only of $\bf{x}=0$
Grasping the meaning of these three properties may be difficult at this point, but they probably become clearer as you improve your understanding of linear algebra.


Euclidean norm:\
The Euclidean norm is one of the most popular norms in machine learning. It is so widely used that sometimes is refered simply as “the norm” of a vector. 

In [ ]:
x=np.array(([3],[4]))
np.linalg.norm(x,2)


5.0

Manhattan norm:\
 the distance between any two points is measured by moving in vertical and horizontals lines (instead of diagonals as in the Euclidean norm).

In [ ]:
np.linalg.norm(x,1)

7.0

Max norm:\
The max norm or infinity norm is simply the absolute value of the largest element in the vector.

In [ ]:
np.linalg.norm(x,np.inf)

4.0

Two vector distance

In [ ]:
#distance of vector x and vector y
dist=np.linalg.norm(x-y,2)
print("distance x and y is", dist)

distance x and y is 0.0


In [ ]:
x , y= np.array([[1],[2]]), np.array([[5],[7]])
cos_theta=(x.T@ y)/(np.linalg.norm(x,2)*np.linalg.norm(y,2))
print(np.round(cos_theta,3))

[[0.988]]


In [ ]:
cos_inv=np.arccos(cos_theta)
print(cos_inv) #radian

[[0.15660188]]


In [ ]:
degree=cos_inv*((180)/np.pi)
print(degree)

[[8.97262661]]


In [ ]:
x=np.array ([[2],[0]])
y=np.array([[0],[2]])
#cos(theat)?  &  theat?

In [ ]:
import numpy as np
import pandas as pd
import altair as alt

In [ ]:
A=np.array([[0,2],
            [1,4]])

B= np.array([[3,1],
             [-3,2]])
C= A+B
#or 
C=np.add(A,B)

Alpha=2
Alpha*A
#or
np.multiply(Alpha,A)

array([[0, 4],
       [2, 8]])

In [ ]:
A@x
#or
np.dot(A,x)

A@B
#or
np.dot(A,B)

array([[4],
       [9]])